### ISSUE TITLE
Clear all bookmarks with d_c

### ISSUE THREAD

**Issue by sathishvj** [huyng/bashmarks#42]
Sometimes I want to clear all bookmarks.  Can you add a d_c option for that?
Maybe even a 'are you sure?' prompt.

**Comment by leogtzr** [comment]
Hi @sathishvj I just added that option to my fork:
https://github.com/leogtzr/bashmarks

```
[0 [21:38][leo@bashmarks]$ d_c 
Remove all bookmarks [y/n] y
```

**Comment by sathishvj** [comment]
Nice.  I've copied that in.  
Thank you.

I'll still leave this issue open though so that @huyng can roll in similar changes.

**Comment by huyng** [comment]
The same result can be achieved by doing a `rm ~/.sdirs` without too much additional effort. We should keep list of supported commands small to minimize the effort needed to learn how to use this tool.
