### ISSUE TITLE
Install and share Bashmarks between multiple user?

### ISSUE THREAD

**Issue by inovek** [huyng/bashmarks#47]
Sorry if this question already aked anywhere... I didn't found it. But can remember that i read something about it in the past.

To share the marks between multiple user... i think it is enough to sync the .sdirs file.
But I would like to know how I've to install Bashmarks to make it usable for all users.

Or did I really have to install it on each user again?

**Comment by daveharris** [comment]
Hi @inovek,

You don't need to install it for each user. It's installed to `/usr/local/bin/bashmarks.sh` which is purposely used for this reason.

In **each** users's `~/.bash_profile`/`~/.bashrc` you just need to add (like normal):
```bash
source /usr/local/bin/bashmarks.sh
```

As for linking the `.sdirs` file, I suggest that you simply use a [symlink](http://en.wikipedia.org/wiki/Symbolic_link) to connect to the two:
```bash
# allow users in your group to read and write the file. If the two users aren't in the same group you will need 666
chmod 664 ~/.sdirs 
# create a symlink between the two files
sudo ln -s ~/.sdirs /Users/user2/.sdirs 
# show the symlink
sudo ls -l /Users/user2/.sdirs 
# it should display something like
# lrwxr-xr-x   1 user2  staff    18 19 May 08:40 /Users/user2/.sdirs -> /Users/user1/.sdirs
```

Let me know how you get on! Happy to help out if it doesn't work.

Dave

**Comment by inovek** [comment]
Greetings, sorry for the long wait.
Yeah I did it like you said and it worked like a charm.

I think this hint could be a nice entry for your wiki or such thing.

At the end I've to thanks for your script itself, too. It has made navigating and working so much more comfortable and I never want to miss this feature ever again.

Good work!
