### ISSUE TITLE
Bashmarks Replacement

### ISSUE THREAD

**Issue by samiconductor** [huyng/bashmarks#65]
If you're looking for a replacement for this project you can use [CDPATH](http://tldp.org/LDP/abs/html/internalvariables.html#CDPATHREF) to give you similar functionally.

**Comment by AnwarShah** [comment]
Good thing to know. But I think this project has it's own usage.

**Comment by svoboda-jan** [comment]
If you want to use shorter names for directories when using [CDPATH](http://tldp.org/LDP/abs/html/internalvariables.html#CDPATHREF) you can use symlinks.

For example, create a directory called `shortcuts`, add it to `CDPATH` and then add symlinks to desired direcories giving them short names.

```bash
export CDPATH="$HOME/Documents:$HOME/shortcuts:$CDPATH"

# add a shortcut
ln -sf ~/some/long/path/and-long-name ~/shortcuts/name

# usage:
cd name
# to see the physical path when you cd:
cd -P name
```
